"""Initial migration

Revision ID: b701ce5254d2
Revises: bb45a7fb3c5b
Create Date: 2025-07-16 17:54:01.086271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b701ce5254d2'
down_revision = 'bb45a7fb3c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upwork_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('client_country', sa.String(length=100), nullable=True),
    sa.Column('client_payment_verified', sa.Boolean(), nullable=True),
    sa.Column('client_total_spent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('client_jobs_posted', sa.Integer(), nullable=True),
    sa.Column('client_hire_rate', sa.String(length=10), nullable=True),
    sa.Column('client_reviews', sa.Text(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('budget_type', sa.Enum('fixed', 'hourly', name='budgettypeenum'), nullable=True),
    sa.Column('project_length', sa.String(length=100), nullable=True),
    sa.Column('hours_per_week', sa.String(length=50), nullable=True),
    sa.Column('proposals_submitted', sa.Integer(), nullable=True),
    sa.Column('interviewing', sa.Integer(), nullable=True),
    sa.Column('invites_sent', sa.Integer(), nullable=True),
    sa.Column('connect_required', sa.Integer(), nullable=True),
    sa.Column('expected_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_earnings', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('job_url', sa.Text(), nullable=False),
    sa.Column('feasibility_status', sa.Enum('pending', 'valid', 'scam', 'unsure', name='feasibilityenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upwork_jobs')
    # ### end Alembic commands ###
